### ISSUE TITLE
Input Data Format

### ISSUE THREAD

**Issue by Iman-sm** [smousavi05/Unsupervised_Deep_Learning#5]
Hi,
I'm trying to convert time domain 3D seismic data (miniseed data) to the specific STFT format required by your model. 
Is it possible to use [scipy.signal.stft()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.stft.html) for this conversion?
Since there are 3 streams of data (for E, N and Z), how would you use this function (and any possible merging operations) on this data to create a *.npy file in a format similar to your x.np.npy which you provided as an example?
Thanks

**Comment by smousavi05** [comment]
Hi @Iman-sm first do you mean 3c (3 components) by 3d? 
Second, yes STFT from scipy works.
About the format, you can just stack the stft of 3c on top of each other. This will make the width and hight of your resulted spectrogram larger but then you can modify networks dimensions. I also recommend to first start by  STFT from only one component for instance Z. Then you can test to see if any of other components or their combination gives you a better reconstruction and clustering results.

**Comment by Iman-sm** [comment]
Thank you very much for the quick reply.
Yes, 3 components. I come from a different background (computer graphics) hence the term 3D. It's good to know the seismology term.
And thank you for the advice. I'll definitely start experimenting with one component.
Regards.
